### ISSUE TITLE
aegisub保存切割音频报错

### ISSUE THREAD

**Issue by kirbystudy** [tumuyan/video-shuffler-for-aegisub#1]
![image](https://user-images.githubusercontent.com/63231787/225539469-2bd0923b-19db-41be-ab70-5e59c93cf6b6.png)

**Comment by tumuyan** [comment]
方便远程协助嘛？我qq连你电脑看下是什么问题

**Comment by kirbystudy** [comment]
感谢大佬，我已经解决了，原因是 "?" 这个符号导致的错误。

**Comment by tumuyan** [comment]
好的。因为是调用命令行处理，所以文件夹、文件名称如果包含特殊符号可能会出错。
